## Error handling in Solidity

### Global functions for Error Handling and Exceptions

- `revert()`
- `require(condition)`
- `assert(condition)`

## Error의 종류

### Runtime Error

- EVM 또는 함수 동작에 의한 오류

### Application Error

- 코드의 오류 또는 데이터의 오류로 인한 오류

## How to handle errors?

- 개발자 각자의 재량
- 오류가 발생하였음을 호출자에게 어떻게 알려줄까?
  1. 특정 값을 반환
  2. 이벤트 발생
  3. 1과 2의 혼합
  4. 예외 던지기 (추천)

## No `Try-Catch`

- 즉, 예외가 발생하게 되면, 해당 예외는 단지 호출자에게 전달되게 된다
- 예외가 발생하면, 해당 거래에서 이루어진 모든 변화들이 롤백되서, 거래가 이루어지기 직전의 상태로 돌아가게 된다
  - 지출된 ETH도 모두 롤백된다
  - 단, *Gas는 여전히 소모된다*
- 해당 거래가 이루어지지 않았더라도, *블록에는 거래가 기록된다(실패한 거래).*

## `revert()`

- 예외를 던지는 함수 (`throw()`와 유사한 것)
  - 예외가 던져지면, 컨트랙트 인스턴스의 동작이 정지되고, 예외는 전파되어 호출자에게 도달한다
  - 아직 미사용된 Gas는 반환된다 (즉, 사용된 만큼만 비용이 청구된다)
- `throw()`가 존재하기는 하지만, deprecated 되었으므로 사용하지 말자

## `require(condition)` / `assert(condition)`

- 조건문을 인자로 받는다
  - 조건문이 `false`로 평가되면, 예외를 던진다
- `require()`은 미사용 가스를 반환하지만, `assert()`는 모든 가스를 소모한다
  - `require()`은 함수 호출자에게 예외를 되돌려줄 때에 주로 사용된다
  - `assert()`는 내부 테스트에서 주로 사용된다
- 조건문이 `false`로 평가되면, 컨트랙트의 동작이 멈추고, 이루어진 모든 변화가 롤백된다
  - 어떤 함수가 실행되기 앞서 선행 조건을 엄밀하게 지키도록 강제할 수 있는 좋은 방법

```sol
pragma solidity >=0.4.24;

contract ExceptionsContract {

    // Public variable lastCaller, with a value of none
    string  public lastCaller = "none";

    // Function revertBehavior that takes in a name as an argument,
    // and sets the lastCaller variable to this argument received
    function  revertBehavior(string memory name) public returns (bool) {
        lastCaller = name;

        // Check if length of the string is zero
        // If the argument received has zero length, it throws an exception...
        // Once an exception is thrown, the variable lastCaller rolls back to its initial value
        if (bytes(name).length == 0) {
            revert("The length of the string is zero");
        }

        // This is the same thing...just using require to check the length of the input string.
        // The code will only be executed if the length is greater than 0
        // The above lines of code may be replaced with this
        // 예외가 던져지는 경우, 두번째 인자가 호출자에게 반환된다
        require(bytes(name).length > 0, "The length of the string is zero");
        // `require()`의 조건을 충족하는 경우, 코드의 다음 라인이 실행된다
        return true;
    }

}

// So, what is going on is that in the function revertBehavior
// lastCaller is being changed to the input argument
// and then an exception is thrown, and the lastCaller reverts back
// to its orginial value, thus nullifying the effect
```
